#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../extlib/lib/perl5";
use lib "$FindBin::Bin/../lib";

use Genome3D::Api::Client;

my $app = Genome3D::Api::Client->new_with_options;

$app->run;
